export const PRODUCTS = [
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "Women's Printed Maxi Skirt",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW Button Front Maxi Dress",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "Exclusively Collection",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "Hot Product",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "Brand Discount's Printed Maxi Skirt Exclusive",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "Button Front Maxi Dress",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW Exclusive Collection",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "Bangladeshi Button Front Maxi Dress",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "Lovely Pure Cotton Dress",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "International Pure Cotton Dress",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "Beauty And Beast Product",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW Women's Printed Tie-Waist",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "Dhaka Exclusive Saree",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW Blue Print Dress",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    }
    // Add more products as needed
];
